<?php $this->headTitle()->prepend($this->translate('My Google Calendar Profile')); ?>

<?php 
    $form = $this->form;
    $form->prepare();
    $form->setAttribute('action', '/google/save');
    $form->setAttribute('method', 'post');
    echo $this->form()->openTag($form);
?>
<div class="container">
    <div class="row">
    <div class="col-lg-12">
        <div class="form-group">
            <h2><i class="fa fa-google"></i> Google Calendar Sync <small><?php echo $this->translate('Set your default public google calendar')?></small></h2>
            <hr/>
            <p><?php echo $this->translate('Here you can control what calendar and events will be shared in this website. When you set your calendar here, the events on that calendar are public as well meaning that people can search for it and find it in a variety of ways, including via Google Web search.')?></p>
            <blockquote><?php echo $this->translate('Set your google calendar public in this page. When you\'ll add a new event the system shows it on the site.')?></blockquote>
            <a class="btn btn-success" href="/google" target="_blank"><i class="fa fa-google"></i> <?php echo $this->translate('Login Google')?></a> 
            <a class="btn btn-danger" href="https://security.google.com/settings/security/permissions" target="_blank"><?php echo $this->translate('Revoke the access to the google calendar')?></a>
            <hr/>
            <?php echo $this->formLabel($form->get('googlecalendar')); ?>
            <?php echo $this->formElement($form->get('googlecalendar')); ?>
            <?php echo $this->formElementErrors($form->get('googlecalendar')); ?>
        </div>
        <div class="alert alert-danger"><i class="fa fa-warning"></i> <?php echo $this->translate('Warning! All the previous events synced will be deleted and synced again!')?></div>
        <div class="text-right">
    	    <?php echo $this->formElement($form->get('submit')); ?>
    	    <a onclick="return confirm('<?php echo $this->translate('Are you sure? All the google calendar preference and events will be deleted! Please login again!') ?>')" href="/google/delete" class="btn btn-danger"><?php echo $this->translate('Disconnect Google Calendar')?></a>
    	</div>
    </div>
    </div>
</div>

<?php echo $this->form()->closeTag() ?>