<!DOCTYPE html>
<html>
    <head>
        <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" media="all" rel="stylesheet" type="text/css">
        <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap-theme.min.css" media="all" rel="stylesheet" type="text/css">
        <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" media="all" rel="stylesheet" type="text/css">
        <script type="text/javascript" src="//code.jquery.com/jquery.min.js"></script>
        <script type="text/javascript">
            $(function() {
                function openUrl(url){
                    var _a=document.getElementById("targetA");
                    _a.href=url;
                    _a.click();
                    window.focus();
                }
                $.getJSON( '/google/connect', function( j ){
                    if(j.oauth){
                        openUrl(j.url);
                    }else{
                        if(j.success){
                        	window.location.href = '/google/calendar';
                        }else{
                        	alert(j.message);
                        }
                    }
                });
            });
        </script>
    </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h1><?php echo $this->translate('Google')?> <small><?php echo $this->translate('Request confirm')?></small></h1>
                    <p><?php echo $this->translate('A popup window will appear to confirm your Google Connection!')?></p><br/>
                    
                    <a class="btn btn-success" href="#" target="_blank" id="targetA"><i class="fa fa-calendar"></i> <?php echo $this->translate('Click here') ?></a>
                    <hr/>
                    
                    <p><?php echo $this->translate("If the window doesn't open ...")?></p>
                    <ul class="list">
                        <li><a href="/google" target="_self" ><?php echo $this->translate('Refresh this page')?></a></li>
                        <li><a href="https://support.mozilla.org/en-US/kb/pop-blocker-settings-exceptions-troubleshooting" target="_blank" >Firefox</a></li>
                        <li><a href="https://support.google.com/chrome/answer/95472?hl=en-GB" target="_blank" >Chrome</a></li>
                        <li><a href="http://support.apple.com/kb/ph11946" target="_blank" >Safari</a></li>
                        <li><a href="http://windows.microsoft.com/en-us/internet-explorer/ie-security-privacy-setting" target="_blank" >Internet Explorer</a></li>
                        <li><a class="" href="/profile"><?php echo $this->translate('Back to the website')?></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </body>
</html>